### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jlarmstrongiv** [snd-lib/snd-lib#1]
こんばんは 👋 hi

I noticed there’s multiple licenses floating around—the MIT license from this repo and the Terms of Service on [snd.dev](https://snd.dev/).  I have questions after reading them.

```
The following acts are prohibited when using the materials.
・Redistributing or selling the materials by itself as unprocessed.
・Using the materials as a sound logo in an unprocessed form as a trademark (including trademark registration).
Use of the materials is prohibited for purposes that are:
・Against the laws and regulations of the public order and good morals.
・Associated with any political, religious, anti-social, or illegal activities.
・Otherwise judged inappropriate by the copyright holder or operator of website Dentsu Inc. (hereinafter referred to as "the company")
```

---

As these unprocessed materials are included in the repo, are actions such as forking, modifying, and contributing to this repo prohibited under the no redistributing clause?  After all, forking the repo and editing it with my friend may be considered distribution. 

---

Do clauses like `Associated with any political, religious, anti-social, or illegal activities` mean I cannot use UI sounds in websites that may include these activities?  So, if I write a blogpost about sustainability or environmentalism on my personal website or business website, would I be unable to use these sounds?  After all, environmentalism is a hot political topic in the United States.

---

In addition, clauses like `Against the laws and regulations of the public order and good morals` are very vague, and invite you to read:

- http://mikepennisi.com/blog/2020/you-may-finally-use-jshint-for-evil/ 
- https://web.archive.org/web/20130203112329/http://dev.hasenj.org/post/3272592502

and other associated articles.

---

Are the materials dual licensed under the terms of use on the website and MIT license?  If so, the previous issues will be a mute point.

Thank you so much for creating such a beautiful sound library!  Your website is the best one I’ve seen in months.

My apologies for asking these persnickety questions—I just need to ensure I abide by your license.

**Comment by snd-lib** [comment]
Hi. こんにちは！

Thank you very much for your comment about the license! We apologize for the confusion caused by the slightly complicated way of defining it.

Basically, we want people to feel free to use, modify or update both libraries and sound assets. On the other hand, we have decided to set the terms of use for sound assets as a disclaimer in order to guarantee the free use of sound assets.

1)source code
We have adapted the MIT License to the library "snd-lib" that we published on gitHub to enable low-code implementation of SND's sound libraries. 
Source code on GitHub is also clearly visible in terms of derivation and contribution, and we welcome developers to update their source code to make it better and more fun.

2)sound assets
We have adapted "Terms of use" which defined on our website for sound files. This is to avoid a situation where the use of the sound asset for a sound logo or a radical political statement would make it difficult for others to use the sound asset, and to allow for objections in case of emergency. It is not intended to restrict use for general political topics (sustainability, environmental protection, etc).

As you have pointed out, determining whether something is political or morally objectionable is a very difficult question. We hope that you will consider that these Terms and Conditions are not intended to restrict, but only to ensure the freedom of users in general.🙏
